### ISSUE TITLE
Return the refresh feature on an analysis page

### ISSUE THREAD

**Issue by spark008** [pwnall/seven#141]
There should be an ajax spinner that refreshes the page with new analysis results.

**Comment by spark008** [comment]
Fixed in https://github.com/pwnall/seven/pull/150

**Comment by pwnall** [comment]
I reopened this because Srini said he tried out the feature and it didn't work. I looked on funprog and saw neither of us deployed the site since December 10, so I think Srini's observation is based on old code. I'll leave this open until we're sure that the fix works as intended, and he's happy with it.

**Comment by pwnall** [comment]
Heh, they should allow multiple assignees.

**Comment by pwnall** [comment]
```
It works and the new UI is much better!
```
